# Generated by Django 5.0.1 on 2025-03-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('left_distance', models.FloatField()),
                ('right_distance', models.FloatField()),
                ('back_distance', models.FloatField()),
                ('alert_level', models.CharField(max_length=10)),
                ('device_id', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
